# coordinator.py

import logging
from typing import Dict, Any, Optional

from langchain_ollama import OllamaLLM

from .technical_translator import TechnicalTranslator
from .prompt_engineer import PromptEngineer
from .code_generator import CodeGenerator
from .code_optimizer import CodeOptimizer

logger = logging.getLogger(__name__)


class Coordinator:
    """
    The Coordinator class acts as the central orchestrator for the intelligent
    multi-agent pipeline. It manages and executes each stage in the code
    generation process in a structured sequence.

    The pipeline may include the following agents:
    1. (Optional) Technical Translator — interprets user task descriptions
       written in natural language or a different language into a consistent
       technical form.
    2. Prompt Engineer — refines and structures the translated input into
       a machine-understandable prompt suitable for LLM processing.
    3. Code Generator — uses an LLM to generate functional source code
       from the engineered prompt.
    4. (Optional) Code Optimizer — enhances the generated code for performance,
       readability, and maintainability.

    The Coordinator ensures that these components are connected,
    and optionally allows shared or independent LLM instances across agents.
    """

    def __init__(
        self,
        llm_config: Optional[Dict[str, Any]] = None,
        use_translator: bool = True,
        use_optimizer: bool = True,
        shared_llm: bool = True,
        cloud_llm: bool = False,
        debug_mode: bool = False,
    ):
        """
        Initialize the Coordinator and configure the LLM and agent components.

        Args:
            llm_config (Optional[Dict[str, Any]]): Custom configuration for the language model.
            use_translator (bool): Enables or disables the Technical Translator stage.
            use_optimizer (bool): Enables or disables the Code Optimizer stage.
            shared_llm (bool): Determines whether all agents share a single LLM instance.
            cloud_llm (bool): If True, uses a cloud-hosted LLM model; otherwise, uses a local model.
            debug_mode (bool): Enables detailed logging for each stage of the pipeline.
        """
        self.debug_mode = debug_mode

        # Step 1: Define the model configuration
        if llm_config:
            self.llm_config = llm_config
        else:
            if cloud_llm:
                # Cloud-hosted LLM configuration
                shared_llm = True
                self.llm_config = {
                    "model": "qwen3-coder:480b-cloud",
                    "temperature": 0.2,
                    "num_ctx": 4096,
                    "num_gpu": 1,
                    "num_predict": 512,
                }
            else:
                # Local LLM configuration
                self.llm_config = {
                    "model": "llama3",
                    "temperature": 0.2,
                    "num_thread": 12,
                    "num_ctx": 4096,
                    "num_predict": 512,
                }

        # Step 2: Initialize a shared LLM instance if required
        llm = None
        if shared_llm:
            llm = OllamaLLM(**self.llm_config)
            if self.debug_mode:
                logger.info("Shared LLM instance created for all agents.")

        # Step 3: Instantiate each agent with appropriate configurations
        self.translator = (
            TechnicalTranslator(debug_mode=self.debug_mode, llm=llm)
            if use_translator
            else None
        )
        self.prompt_engineer = PromptEngineer(debug_mode=self.debug_mode, llm=llm)
        self.generator = CodeGenerator(debug_mode=self.debug_mode, llm=llm)
        self.optimizer = (
            CodeOptimizer(debug_mode=self.debug_mode) if use_optimizer else None
        )

    def run(self, task_description: str) -> Dict[str, Any]:
        """
        Execute the entire multi-agent code generation pipeline.

        This method runs the process from natural-language task description
        to final optimized source code, handling all intermediate results and
        possible exceptions at each stage.

        Args:
            task_description (str): The initial problem statement or task description.

        Return:
            Dict[str, Any]: A structured dictionary containing:
                - "input": Original task description.
                - "translated": Output of the Technical Translator (if used).
                - "spec": Structured prompt specification from the Prompt Engineer.
                - "generated_code": Raw code generated by the LLM.
                - "optimized_code": Enhanced code from the optimizer (if used).
                - "final_code": The final output code (optimized or raw).
                - "error": Any error encountered during execution.
        """
        result: Dict[str, Any] = {
            "input": task_description,
            "translated": None,
            "spec": None,
            "generated_code": None,
            "optimized_code": None,
            "final_code": None,
            "error": None,
        }

        try:
            # Step 1: Optional translation stage
            if self.translator:
                try:
                    translated = self.translator.run(task_description)
                    # Safe error handling: if translation fails return original
                    if isinstance(translated, dict) and translated.get("error"):
                        # Agent returned an error dict
                        result["error"] = translated.get("error")
                        result["translated"] = (
                            task_description  # Fallback to original input on translation error
                        )
                        logger.error("Translator returned error: %s", translated.get("error"))
                        return result
                    result["translated"] = translated
                    if self.debug_mode:
                        logger.debug(f"[Translator Output] {translated}")
                except Exception as e:
                    logger.exception(f"Translator failed: {e}")
                    result["error"] = f"Translator error: {str(e)}"
                    return result
            else:
                translated = (
                    task_description  # Use raw description if no translator is used
                )

            # Step 2: Prompt engineering stage
            try:
                spec = self.prompt_engineer.run(translated)
                # Safe error handling: spec might be a dict with/without "error" or a valid spec dict
                if isinstance(spec, dict) and spec.get("error"):
                    # Agent returned an error dict
                    result["error"] = spec.get("error")
                    result["spec"] = spec  # keep raw for debugging
                    logger.error("PromptEngineer returned error: %s", spec.get("error"))
                    return result
                result["spec"] = spec
                if self.debug_mode:
                    logger.debug(f"[PromptEngineer Output] {spec}")
            except Exception as e:
                logger.exception(f"PromptEngineer failed: {e}")
                result["error"] = f"PromptEngineer error: {str(e)}"
                return result

            # Step 3: Code generation stage
            try:
                code = self.generator.run(spec)
                # Safe error handling: if generation fails
                if isinstance(code, dict) and code.get("error"):
                    # Agent returned an error dict
                    result["error"] = code.get("error")
                    result["generated_code"] = translated  # keep raw for debugging
                    logger.error("CodeGenerator returned error: %s", code.get("error"))
                    return result
                result["generated_code"] = code
                if self.debug_mode:
                    logger.debug(f"[CodeGenerator Output] {code}")
            except Exception as e:
                logger.exception(f"CodeGenerator failed: {e}")
                result["error"] = f"CodeGenerator error: {str(e)}"
                return result

            # Step 4: Optional optimization stage
            if self.optimizer:
                try:
                    optimized_code, result_info = self.optimizer.run(code)
                    if self.debug_mode:
                        logger.debug(
                            f"[Optimizer Output] {optimized_code, result_info}"
                        )
                    if result_info["success"] == False:
                        result["error"] = result_info["error"]
                        result["final_code"] = code
                        return result
                except Exception as e:
                    logger.warning(f"Optimizer failed: {e}")
                    result["error"] = f"Optimizer error: {str(e)}"
                    result["final_code"] = code
                    return result
                result["optimized_code"] = optimized_code
                result["final_code"] = optimized_code
            else:
                # Use unoptimized code as a fallback
                result["final_code"] = code

        except Exception as e:
            logger.critical(f"Unexpected pipeline failure: {e}")
            result["error"] = f"Pipeline error: {str(e)}"
        return result
